version: "3.7"

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV-development}
    command: npx parcel -p 8080 --no-hmr src/index.html
    ports:
      - "8080:8080" # Application Port
      # - "8081:8081" # Hot Reload Module
    tty: true
    environment:
      - NODE_ENV=${NODE_ENV-development}
    volumes:
      - ./:/usr/app
      - node_modules:/usr/app/node_modules

volumes:
  node_modules:
