version: "3.7"

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV-development}
    ports:
      - "8080:8080" # Application Port
      - "3000:3000" # Browser Sync Proxy
      - "3001:3001" # Browser Sync Server
    tty: true
    environment:
      - NODE_ENV=${NODE_ENV-development}
    volumes:
      - ./:/usr/app
      - node_modules:/usr/app/node_modules

volumes:
  node_modules:
